# Generated by Django 4.0.2 on 2022-03-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-title', 'id')},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XL', 'Xtra_Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('XS', 'Xtra_Small')], max_length=200),
        ),
    ]
