# Generated by Django 4.0.2 on 2022-03-10 10:19

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_product_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(upload_to=''),
        ),
    ]
