# Generated by Django 4.0.2 on 2022-03-14 09:17

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
